2020-09-24 23:58:26.136990: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-09-24 23:58:26.145545: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2020-09-24 23:58:26.146450: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: gruselglatz
2020-09-24 23:58:26.146757: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: gruselglatz
2020-09-24 23:58:26.147098: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 440.59.0
2020-09-24 23:58:26.147402: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 440.59.0
2020-09-24 23:58:26.147656: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 440.59.0
Traceback (most recent call last):
  File "../exps/si_test.py", line 181, in <module>
    result_dicts.append(experiment.train(rnn_config, labelled_data_config, training_config, info_config, run))
  File "../src/experiment.py", line 123, in train
    self.rnn.t_metrics.print(session_idx)
  File "../src/data/t_metrics.py", line 171, in print
    self.result_dict['va_s']['loss'][-1]))
OSError: [Errno 5] Input/output error
rm: write error: Input/output error
