2019-11-21 14:39:26.209745: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-11-21 14:39:26.217456: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-11-21 14:39:26.217617: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: capri
2019-11-21 14:39:26.217671: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: capri
2019-11-21 14:39:26.217795: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.104.0
2019-11-21 14:39:26.217869: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.104.0
2019-11-21 14:39:26.217914: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.104.0
Traceback (most recent call last):
  File "../exps/si_test.py", line 150, in <module>
    result_dicts.append(experiment.train(rnn_config, labelled_data_config, training_config, info_config, run))
  File "../src/experiment.py", line 124, in train
    self.rnn.t_metrics.retrieve_results(sess, current_epoch, tau)
  File "../src/data/t_metrics.py", line 171, in print
    self.result_dict['va_s']['loss'][-1]))
OSError: [Errno 5] Input/output error
rm: write error: Input/output error
