2019-08-19 14:55:42.718271: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-08-19 14:55:42.833099: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 960 major: 5 minor: 2 memoryClockRate(GHz): 1.2405
pciBusID: 0000:03:00.0
totalMemory: 3.95GiB freeMemory: 3.86GiB
2019-08-19 14:55:42.833202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-08-19 14:55:46.684320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-19 14:55:46.684431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-08-19 14:55:46.684484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-08-19 14:55:46.686679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3587 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960, pci bus id: 0000:03:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "../exps/mter_test.py", line 151, in <module>
    result_dicts.append(experiment.train(rnn_config, labelled_data_config, training_config, pretrain_config, info_config))
  File "../src/experiment.py", line 172, in train
    model_saver.save(sess, temp_model_path)
  File "/clusterFS/home/student/kopp13/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1620, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/clusterFS/home/student/kopp13/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/clusterFS/home/student/kopp13/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1023, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.
