2019-10-17 17:25:39.691758: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-10-17 17:25:39.701323: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-10-17 17:25:39.701448: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: nina
2019-10-17 17:25:39.701521: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: nina
2019-10-17 17:25:39.701639: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.104.0
2019-10-17 17:25:39.701714: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.104.0
2019-10-17 17:25:39.701766: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.104.0
Traceback (most recent call last):
  File "../exps/mter_test.py", line 152, in <module>
    result_dicts.append(experiment.train(rnn_config, labelled_data_config, training_config, info_config, run))
  File "../src/experiment.py", line 118, in train
    self.save_gradient_variance(sess, epoch, tau)
  File "../src/experiment.py", line 202, in save_gradient_variance
    for grad, var in self.rnn.gradients:
TypeError: 'NoneType' object is not iterable
